apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-users
  namespace: messager
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z postgres 5432; do echo "waiting..."; sleep 3; done
        - name: copy-migrations
          image: mablinov2704/user-service:latest
          command: ["cp", "-r", "/app/migrations/.", "/migrations/"]
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      containers:
        - name: migrate-users
          image: ghcr.io/kukymbr/goose-docker:3.24.2
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: USER_DB_DSN
            - name: GOOSE_MIGRATION_DIR
              value: /migrations
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          emptyDir: {}
